/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: noortjeschuur (https://sketchfab.com/noortjeschuur)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/button-54d1a97dd6a44322817d3fff64b986fd
Title: button
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Button(props) {
  const { nodes, materials } = useGLTF("/../assets/button.glb");
  return (
    <group {...props} dispose={null} position={[2, 0, 6]} scale={0.4}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder9_defaultPolygonShader_0.geometry}
        material={materials.defaultPolygonShader}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder10_defaultPolygonShader_0.geometry}
        material={materials.defaultPolygonShader}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/../assets/button.glb");
