/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: noortjeschuur (https://sketchfab.com/noortjeschuur)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/button-54d1a97dd6a44322817d3fff64b986fd
Title: button
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ToonMaterial } from "../material/ToonMaterial";
import VisibleEdges from "../material/Edges";

export function Button(props) {
  const { nodes, materials } = useGLTF("/../assets/button.glb");
  return (
    <group {...props} dispose={null} position={[2, 0.07, 6]} scale={0.4}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder9_defaultPolygonShader_0.geometry}
        scale={0.01}
      >
        <ToonMaterial color={"#d8f5b8"} />
        <VisibleEdges color="black" threshold={5} baseLineWidth={5} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder10_defaultPolygonShader_0.geometry}
        scale={0.01}
      >
        <ToonMaterial color={"#ff6152"} />
        <VisibleEdges color="black" threshold={5} baseLineWidth={5} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/../assets/button.glb");
