/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TVdot (https://sketchfab.com/TVdot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-small-ceiling-plane-2162f5739b3d4ddfabc405d0919dcd36
Title: Sci-Fi Small Ceiling (Plane)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ToonMaterial } from "../material/ToonMaterial";
import VisibleEdges from "../material/Edges";

export function CeilingTile({ position }) {
  const { nodes, materials } = useGLTF("../assets/sci-fi_modular_ceiling.glb");
  console.log("test");
  return (
    <group dispose={null} position={position} scale={0.008}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.GD47Vrushank_CEILINGblinn14SG}
        position={[243.224, 339.397, 0]}
        rotation={[-Math.PI / 2, -1.562, 0]}
      >
        <ToonMaterial color={"#7baae8"} />
        <VisibleEdges color="black" threshold={5} baseLineWidth={15} />
      </mesh>
    </group>
  );
}

useGLTF.preload("../assets/sci-fi_modular_ceiling.glb");
