/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Constantin Iosef (https://sketchfab.com/constantin.iosef)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/envart-scifi-floor-tile-3-3a22a02446104089b6c059455b67792a
Title: [EnvArt] Scifi Floor Tile 3
*/

import * as THREE from "three";
import React, { useRef, useEffect, useState } from "react";
import { ToonMaterial } from "../material/ToonMaterial";
import VisibleEdges from "../material/Edges";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Floor() {
  const [isFloorReady, setIsFloorReady] = useState(false);
  const floor = useRef();
  const [worldPosition, setWorldPosition] = useState(new THREE.Vector3());
  const { nodes, materials } = useGLTF("/../assets/floortile.glb");

  useEffect(() => {
    if (floor.current) {
      const tempWorldPosition = new THREE.Vector3();
      floor.current.getWorldPosition(tempWorldPosition);
      setWorldPosition(tempWorldPosition);
      setIsFloorReady(true);
    }
  }, [floor.current]);

  return (
    <group
      dispose={null}
      position={[0, 0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    >
      <group scale={0.006}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["EViRO_Kuby_��������_0"].geometry}
          material={materials.material}
          position={[0, 0, -8.893]}
          ref={floor}
        >
          <ToonMaterial color={"#aeb2c2"} />
          {isFloorReady && (
            <VisibleEdges
              color="black"
              threshold={40}
              baseLineWidth={5}
              otherParent={true}
              parentPosition={worldPosition}
            />
          )}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/../assets/floortile.glb");
