/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KainHunter1997 (https://sketchfab.com/KainHunterDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sm-jumppad-7a41b91af23b4a7db4579677666c7f14
Title: SM_JumpPad
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function JumpPad(props) {
  const { nodes, materials } = useGLTF("../assets/sm_jumppad.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.JumpPad_M_JumpPad_0.geometry}
          material={materials.M_JumpPad}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.JumpPadBeam_M_JumpPadBeam_0.geometry}
          material={materials.M_JumpPadBeam}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../assets/sm_jumppad.glb");
