/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Inditrion Dradnon (https://sketchfab.com/dradnon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-energy-conduit-system-fb4046a17dac4d5d82808348900b081c
Title: Sci-Fi Energy Conduit System
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ToonMaterial } from "../material/ToonMaterial";
import VisibleEdges from "../material/Edges";
import { RigidBody, CuboidCollider } from "@react-three/rapier";

export function Pipes({ position, rotation, scale = 0.1 }) {
  const { nodes, materials } = useGLTF(
    "/../assets/sci-fi_energy_conduit_system.glb"
  );

  return (
    <>
      <group
        dispose={null}
        scale={scale}
        position={position}
        rotation={rotation}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MaterialFBXASC032FBXASC0352142150746_6.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150746}
              position={[-0.012, 0, -21.312]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <ToonMaterial color={"#7baae8"} />
              <VisibleEdges color="black" threshold={20} baseLineWidth={15} />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MaterialFBXASC032FBXASC03511294_6.geometry}
              material={materials.MaterialFBXASC032FBXASC03511294}
              position={[-0.012, 0, -21.312]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <ToonMaterial color={"#c4cef2"} />
            </mesh>
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} position={[0, 0, 20]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MaterialFBXASC032FBXASC0352142150746_6.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150746}
              position={[-0.012, 0, -21.312]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <ToonMaterial color={"#7baae8"} />
              <VisibleEdges color="black" threshold={20} baseLineWidth={15} />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MaterialFBXASC032FBXASC03511294_6.geometry}
              material={materials.MaterialFBXASC032FBXASC03511294}
              position={[-0.012, 0, -21.312]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <ToonMaterial color={"#c4cef2"} />
            </mesh>
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} position={[0, 0, 10]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MaterialFBXASC032FBXASC0352142150746_6.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150746}
              position={[-0.012, 0, -21.312]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <ToonMaterial color={"#7baae8"} />
              <VisibleEdges color="black" threshold={20} baseLineWidth={15} />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MaterialFBXASC032FBXASC03511294_6.geometry}
              material={materials.MaterialFBXASC032FBXASC03511294}
              position={[-0.012, 0, -21.312]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <ToonMaterial color={"#c4cef2"} />
            </mesh>
          </group>
        </group>
        <RigidBody type="fixed" colliders={false}>
          <CuboidCollider args={[21, 13, 1.5]} position={[24.6, 10, -20]} />
        </RigidBody>
      </group>
    </>
  );
}

useGLTF.preload("/../assets/sci-fi_energy_conduit_system.glb");
