/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vasko Petrov (https://sketchfab.com/vaskopetrov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-gun-2983dac401d741349ff35ff91a1786f0
Title: Stylized Gun
*/

import React, { useRef } from "react";
import { useGLTF, Edges } from "@react-three/drei";

export function Gun(props) {
  const { nodes, materials } = useGLTF("../assets//stylized_gun.glb");
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.material}
        position={[0, 0.716, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.material}
        position={[0, -1.471, -3.499]}
        rotation={[0.272, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.material}
        position={[0, -1.471, -3.499]}
        rotation={[0.272, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.material}
        position={[0, -0.311, 2.111]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.material}
        position={[0, 0.735, -0.193]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.material}
        position={[0, -1.471, -3.499]}
        rotation={[0.272, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.material}
        position={[0, 0.748, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.material}
        position={[0.103, 0.05, 0]}
        rotation={[0, 0, -1.625]}
      />
      <mesh
        layers={3}
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.material}
        position={[0, 0.716, -0.218]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("../assets/stylized_gun.glb");
